### ISSUE TITLE
File Handling API appears broken (Edge 102.0.1245.39)

### ISSUE THREAD

**Issue by Jaifroid** [captainbrosset/mytracks#1]
I have Edge 102.0.1245.39 on Windows 11. I followed the instructions on the [Microsoft explainer](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files), i.e.:

* I enabled the File Handling API in edge://flags
* I installed the My Tracks app
* Edge confirmed it had been installed and integrated with the OS
* I downloaded the test GPX file
* I double-clicked it: a "look for an app to open this file" dialog appears (My Tracks is not listed)
* I right-click the GPX file and select "open with": there is no option to open the file with My Tracks

What am I doing wrong?

**Comment by captainbrosset** [comment]
Thanks for filing this. It seems to be a problem with my app. The API might have changed a bit. Now when I open DevTools (Application panel), I see the `Invalid MIME type */*, FileHandler ignored. Property accept is invalid` error, which explains why Windows is not letting you open the file with this app.
I'll fix this.

**Comment by captainbrosset** [comment]
File association now works. I replace the invalid `*/*` mime-type with `text/xml` and that did the trick.
Now, I've got another problem which is that opening the file starts the app and goes to `/mytracks/index.html/?activation=file` for some reason, and that makes my app go to a 404 error.
But this is separate, so I'll close this issue now.
